application: dgdsitterid
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico
  
- url: /stylesheets
  static_dir: stylesheets

- url: /sitterForm.html
  static_files: sitterForm.html
  upload: sitterForm.html
- url: /parentForm.html
  static_files: parentForm.html
  upload: parentForm.html
  
# Endpoints handler
- url: /_ah/spi/.*
  script: helloworld_api.APPLICATION

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
- name: pycrypto
  version: latest
- name: endpoints
  version: 1.0